language: R
sudo: false
cache: packages

warnings_are_errors: false

pandoc: false

before_install:
  - cd rdev

r_packages:
  - roxygen2
  - devtools
  - RcppArmadillo

os:
  - linux

script:
  - cd ../
  - mkdir Rchecks
  - make travis_build
  - make check
