language: R
sudo: false
cache: packages

warnings_are_errors: false

pandoc: false

r_packages:
  - roxygen2
  - devtools
  - RcppArmadillo

os:
  - linux

script:
  - mkdir Rchecks
  - make check 


